### ISSUE TITLE
view-source:https://hstspreload.org/?domain=cloudapis.googleapis.com#:~:text=Domain%20error%3A%20The,for%20your%20site.

### ISSUE THREAD

**Issue by davidfletcher7** [pageboard/proxy#14]
view-source:https://hstspreload.org/?domain=cloudapis.googleapis.com#:~:text=Domain%20error%3A%20The,for%20your%20site.

_Originally posted by @davidfletcher7 in https://github.com/pageboard/proxy/issues/7#issuecomment-1098492049_

**Comment by kapouer** [comment]
That doesn't make any sense. Closing.
