### ISSUE TITLE
HSTS preload list submission

### ISSUE THREAD

**Issue by kapouer** [pageboard/proxy#7]
https://hstspreload.org/?domain=pageboard.fr
https://hstspreload.org/?domain=pageboard.io

**Comment by davidfletcher7** [comment]
view-source:https://hstspreload.org/?domain=cloudapis.googleapis.com#:~:text=Domain%20error%3A%20The,for%20your%20site.

**Comment by kapouer** [comment]
Speaking of which, pageboard.fr is preloaded, and i just added pageboard.io.
